"""added content  and filename parameter to File model

Revision ID: 062a503dafcc
Revises: 72fd2b7ed983
Create Date: 2025-08-06 17:03:04.710573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '062a503dafcc'
down_revision: Union[str, Sequence[str], None] = '72fd2b7ed983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False)) # type: ignore
    op.add_column('file', sa.Column('content', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'content')
    op.drop_column('file', 'filename')
    # ### end Alembic commands ###
