"""check for relationship changes

Revision ID: 3245bfaeb87c
Revises: b61161f8fb92
Create Date: 2025-08-14 14:54:13.173590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3245bfaeb87c'
down_revision: Union[str, Sequence[str], None] = 'b61161f8fb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_topic_question_id'), table_name='question_topic')
    op.drop_index(op.f('ix_question_topic_topic_id'), table_name='question_topic')
    op.drop_table('question_topic')
    op.drop_index(op.f('ix_question_id'), table_name='question')
    op.create_index(op.f('ix_question_id'), 'question', ['id'], unique=False)
    op.drop_index(op.f('ix_topic_name'), table_name='topic')
    op.create_index(op.f('ix_topic_name'), 'topic', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_name'), table_name='topic')
    op.create_index(op.f('ix_topic_name'), 'topic', ['name'], unique=False)
    op.drop_index(op.f('ix_question_id'), table_name='question')
    op.create_index(op.f('ix_question_id'), 'question', ['id'], unique=1)
    op.create_table('question_topic',
    sa.Column('question_id', sa.CHAR(length=32), nullable=False),
    sa.Column('topic_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'topic_id')
    )
    op.create_index(op.f('ix_question_topic_topic_id'), 'question_topic', ['topic_id'], unique=False)
    op.create_index(op.f('ix_question_topic_question_id'), 'question_topic', ['question_id'], unique=False)
    # ### end Alembic commands ###
