"""Added users to the question model

Revision ID: 7df0bdc5afb4
Revises: 062a503dafcc
Create Date: 2025-08-08 12:57:35.285452

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7df0bdc5afb4"
down_revision: Union[str, Sequence[str], None] = "062a503dafcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_question_user_id_users",
            referent_table="user",
            local_cols=["user_id"],
            remote_cols=["id"],
            ondelete="CASCADE",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.drop_constraint("fk_question_user_id_users", type_="foreignkey")
    # ### end Alembic commands ###
