"""Adding topic to database and definining relationship to question

Revision ID: 8bf0196ba457
Revises: 63ac222b3f26
Create Date: 2025-08-14 14:07:14.466579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8bf0196ba457'
down_revision: Union[str, Sequence[str], None] = '63ac222b3f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'topic')
    op.add_column('topic', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False)) # type: ignore
    op.create_index(op.f('ix_topic_name'), 'topic', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_name'), table_name='topic')
    op.drop_column('topic', 'name')
    op.add_column('question', sa.Column('topic', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
