"""Creating linkage between the question and topic

Revision ID: 8dfab66332dd
Revises: f11091b013fa
Create Date: 2025-08-14 14:13:41.578211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8dfab66332dd'
down_revision: Union[str, Sequence[str], None] = 'f11091b013fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questiontopic',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'topic_id')
    )
    op.create_index(op.f('ix_questiontopic_question_id'), 'questiontopic', ['question_id'], unique=False)
    op.create_index(op.f('ix_questiontopic_topic_id'), 'questiontopic', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questiontopic_topic_id'), table_name='questiontopic')
    op.drop_index(op.f('ix_questiontopic_question_id'), table_name='questiontopic')
    op.drop_table('questiontopic')
    # ### end Alembic commands ###
