"""Creating linkage between the question and topic

Revision ID: ae8f64ae9c5a
Revises: 3245bfaeb87c
Create Date: 2025-08-14 14:56:49.761953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae8f64ae9c5a'
down_revision: Union[str, Sequence[str], None] = '3245bfaeb87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
