"""Initial Migration

Revision ID: c5e8c617ff4c
Revises:
Create Date: 2025-08-08 16:19:32.873668

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c5e8c617ff4c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

UC_NAME = "uq_user_email"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", recreate="always") as batch_op:
        batch_op.create_unique_constraint(UC_NAME, ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", recreate="always") as batch_op:
        batch_op.drop_constraint(UC_NAME, type_="unique")
    # ### end Alembic commands ###
