"""Initial migration

Revision ID: ce23ba5b9ea9
Revises:
Create Date: 2025-08-19 17:03:03.507093

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "ce23ba5b9ea9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "language",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_language_name"), "language", ["name"], unique=True)
    op.create_table(
        "qtype",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_qtype_name"), "qtype", ["name"], unique=True)
    op.create_table(
        "question_language_link",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("language_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["language.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.PrimaryKeyConstraint("question_id", "language_id"),
    )
    op.create_index(
        op.f("ix_question_language_link_language_id"),
        "question_language_link",
        ["language_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_language_link_question_id"),
        "question_language_link",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "question_qtype_link",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("qtype_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["qtype_id"],
            ["qtype.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.PrimaryKeyConstraint("question_id", "qtype_id"),
    )
    op.create_index(
        op.f("ix_question_qtype_link_qtype_id"),
        "question_qtype_link",
        ["qtype_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_qtype_link_question_id"),
        "question_qtype_link",
        ["question_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_questiontopiclink_question_id"), table_name="questiontopiclink"
    )
    op.drop_index(op.f("ix_questiontopiclink_topic_id"), table_name="questiontopiclink")
    op.drop_table("questiontopiclink")
    op.drop_column("question", "language")
    op.drop_column("question", "qtype")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("question", sa.Column("qtype", sqlite.JSON(), nullable=True))
    op.add_column("question", sa.Column("language", sqlite.JSON(), nullable=True))
    op.create_table(
        "questiontopiclink",
        sa.Column("question_id", sa.CHAR(length=32), nullable=False),
        sa.Column("topic_id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topic.id"],
        ),
        sa.PrimaryKeyConstraint("question_id", "topic_id"),
    )
    op.create_index(
        op.f("ix_questiontopiclink_topic_id"),
        "questiontopiclink",
        ["topic_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_questiontopiclink_question_id"),
        "questiontopiclink",
        ["question_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_question_qtype_link_question_id"), table_name="question_qtype_link"
    )
    op.drop_index(
        op.f("ix_question_qtype_link_qtype_id"), table_name="question_qtype_link"
    )
    op.drop_table("question_qtype_link")
    op.drop_index(
        op.f("ix_question_language_link_question_id"),
        table_name="question_language_link",
    )
    op.drop_index(
        op.f("ix_question_language_link_language_id"),
        table_name="question_language_link",
    )
    op.drop_table("question_language_link")
    op.drop_index(op.f("ix_qtype_name"), table_name="qtype")
    op.drop_table("qtype")
    op.drop_index(op.f("ix_language_name"), table_name="language")
    op.drop_table("language")
    # ### end Alembic commands ###
