"""Creating linkage between the question and topic

Revision ID: fc377ccd59af
Revises: 70864ee06fe2
Create Date: 2025-08-14 16:34:12.010422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc377ccd59af'
down_revision: Union[str, Sequence[str], None] = '70864ee06fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_topic_question_id'), table_name='question_topic')
    op.drop_index(op.f('ix_question_topic_topic_id'), table_name='question_topic')
    op.drop_table('question_topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_topic',
    sa.Column('question_id', sa.CHAR(length=32), nullable=False),
    sa.Column('topic_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'topic_id')
    )
    op.create_index(op.f('ix_question_topic_topic_id'), 'question_topic', ['topic_id'], unique=False)
    op.create_index(op.f('ix_question_topic_question_id'), 'question_topic', ['question_id'], unique=False)
    # ### end Alembic commands ###
